### ISSUE TITLE
add order to @Result table

### ISSUE THREAD

**Issue by rpagyc** [drumsta/sql-generate-insert#4]
Hi. Thanks for this script. It would be nice to have an order in @Result table. 
SELECT *
  FROM @Results;
**ORDER BY R_ID;** 
I faced the problem when "SET IDENTITY_INSERT OFF" is generated between the insert statements.

**Comment by drumsta** [comment]
Hi Roman,

The sort feature has been added in Build 4. https://github.com/drumsta/sql-generate-insert/commit/bd682f96d30cc47e1ba19ff6c1b9492f18905f16

**Comment by firasr** [comment]
This seems not resolved yet. I took the latest version and the results comes unsorted as @rpagyc mentioned; i.e. "SET IDENTITY_INSERT OFF" is generated between the insert statements.

**Comment by zhaoxiaoming99** [comment]
The order is not quite stable in some cases, I often get this issue when I want to compare the new generated script but it seems some of the rows is not sortted correctly.
