### ISSUE TITLE
Support for execute user defined functions

### ISSUE THREAD

**Issue by seba123neo** [drumsta/sql-generate-insert#5]
Excelent script

is possible to add support for execute user defined functions ?

I need to execute a query like this:

SELECT * FROM dbo.getClients('CITY')

dbo.getClients is the function name

**Comment by drumsta** [comment]
Hi Sebastián @seba123neo,

Build 6 now supports queries from a user defined functions. 3c668c71bf1b4f7ab7c39db3aeefa3716b9fa2f9
